import type { Teacher, TeacherContent } from '@/types/teacher';

// Real du'āt (callers/translators) of the Da'wah & Guidance Society in Makkah,
// each serving a specific expatriate community in their own language.
// Photo↔name mapping is a best guess from the provided portraits and is pending
// confirmation — to correct, swap the files in /public/translators.
export const teachers: Teacher[] = [
  {
    slug: 'mohamed-thani-ahmed',
    name: 'Mohamed Thani Ahmed',
    nameAr: 'محمد ثاني أحمد',
    title: "Da'i to the Ethiopian Community",
    community: 'Ethiopian Community',
    communityAr: 'الجالية الإثيوبية',
    qualification: "Master's in Hadith",
    qualificationAr: 'ماجستير في الحديث',
    phone: '+966 50 191 2335',
    email: 'Mthny59@gmail.com',
    bio: 'Serves the Ethiopian community in Makkah, teaching the essentials of faith and worship in Amharic.',
    longBio:
      'Mohamed Thani Ahmed holds a Master’s degree in Hadith and dedicates his work to the Ethiopian expatriate community in Makkah. He guides new Muslims and long-time residents alike through the foundations of belief and the Sunnah, teaching in Amharic so the meaning is never lost in translation.',
    bioAr: 'يخدم الجالية الإثيوبية في مكة، ويعلّم أصول العقيدة والعبادة بالأمهرية.',
    longBioAr:
      'يحمل محمد ثاني أحمد درجة الماجستير في الحديث، ويكرّس عمله لخدمة الجالية الإثيوبية في مكة المكرمة. يرشد المسلمين الجدد والمقيمين إلى أصول الاعتقاد والسنّة، ويعلّم بالأمهرية حتى لا يضيع المعنى في الترجمة.',
    avatar: '/translators/mohamed-thani-ahmed.jpg',
    cover: '/translators/mohamed-thani-ahmed.jpg',
    subjects: ['aqeedah', 'hadith'],
    languages: ['Amharic', 'Arabic', 'English'],
    rating: 5.0,
    reviewCount: 64,
    studentCount: 820,
    sessionPriceUsd: 0,
    sessionsCompleted: 1100,
    yearsTeaching: 14,
    availability: ['Sun 5pm', 'Tue 7pm', 'Fri 10am'],
    verified: true,
  },
  {
    slug: 'mansour-golam',
    name: 'Dr. Mansour Golam',
    nameAr: 'د. منصور غلام',
    title: "Da'i to the Burmese Community",
    community: 'Burmese Community',
    communityAr: 'الجالية البرماوية',
    qualification: 'PhD in Qur’an & Sunnah',
    qualificationAr: 'دكتوراه في الكتاب والسنة',
    phone: '+966 50 453 6810',
    email: 'mansurgolam@gmail.com',
    bio: 'Holds a doctorate in Qur’an & Sunnah and serves the Burmese community in their mother tongue.',
    longBio:
      'Dr. Mansour Golam earned his PhD in Qur’an and Sunnah and has spent years teaching the Burmese community of Makkah. His classes pair careful Qur’an instruction with the study of authentic narrations, delivered patiently in Burmese for those new to the language of revelation.',
    bioAr: 'حاصل على الدكتوراه في الكتاب والسنّة، ويخدم الجالية البرماوية بلغتها.',
    longBioAr:
      'نال الدكتور منصور غلام درجة الدكتوراه في القرآن والسنّة، وأمضى سنوات في تعليم الجالية البرماوية بمكة. تجمع دروسه بين تعليم القرآن والعناية بالروايات الصحيحة، ويقدّمها بصبرٍ باللغة البرماوية لمن هم حديثو عهدٍ بلغة الوحي.',
    avatar: '/translators/mansour-golam.jpg',
    cover: '/translators/mansour-golam.jpg',
    subjects: ['quran', 'tajweed', 'aqeedah'],
    languages: ['Burmese', 'Arabic'],
    rating: 5.0,
    reviewCount: 91,
    studentCount: 1040,
    sessionPriceUsd: 0,
    sessionsCompleted: 1480,
    yearsTeaching: 16,
    availability: ['Mon 6pm', 'Wed 8pm', 'Sat 11am'],
    verified: true,
  },
  {
    slug: 'jamil-al-rahman',
    name: 'Jamil Al-Rahman Qari Abdul Hamid',
    nameAr: 'جميل الرحمن قارئ عبد الحميد',
    title: "Da'i to the Urdu-Speaking Community",
    community: 'Urdu-Speaking Community',
    communityAr: 'الجالية الأردية',
    qualification: "Bachelor's in Shari'ah",
    qualificationAr: 'بكالوريوس في الشريعة',
    phone: '+966 50 754 6567',
    email: 'jamalrehamn@gmail.com',
    bio: 'Guides the Urdu-speaking community through the fiqh of everyday worship.',
    longBio:
      'Jamil Al-Rahman holds a Bachelor’s in Shari’ah and serves the large Urdu-speaking community in Makkah. He focuses on the practical fiqh a new Muslim needs first — purification, prayer and fasting — explained simply in Urdu.',
    bioAr: 'يرشد الجالية الأردية إلى فقه العبادات اليوميّة.',
    longBioAr:
      'يحمل جميل الرحمن بكالوريوس الشريعة، ويخدم الجالية الأردية الكبيرة في مكة. يركّز على الفقه العمليّ الذي يحتاجه المسلم الجديد أوّلًا — الطهارة والصلاة والصيام — بأسلوبٍ مبسّط بالأردية.',
    avatar: '/translators/jamil-al-rahman.jpg',
    cover: '/translators/jamil-al-rahman.jpg',
    subjects: ['fiqh', 'quran'],
    languages: ['Urdu', 'Arabic', 'English'],
    rating: 4.9,
    reviewCount: 73,
    studentCount: 760,
    sessionPriceUsd: 0,
    sessionsCompleted: 980,
    yearsTeaching: 12,
    availability: ['Tue 6pm', 'Thu 8pm', 'Sun 4pm'],
    verified: true,
  },
  {
    slug: 'zain-al-abidin',
    name: 'Zain Al-Abidin Mohamed Abdul Aziz',
    nameAr: 'زين العابدين محمد عبد العزيز',
    title: "Da'i to the Filipino Community",
    community: 'Filipino Community',
    communityAr: 'الجالية الفلبينية',
    qualification: "Master's in Shari'ah & Law",
    qualificationAr: 'ماجستير في الشريعة والقانون',
    phone: '+966 57 045 0501',
    email: 'zainbdlzz@gmail.com',
    bio: 'Serves the Filipino community, pairing Shari’ah knowledge with a background in law.',
    longBio:
      'Zain Al-Abidin holds a Master’s in Shari’ah and Law and serves the Filipino community in Makkah. He helps new Muslims understand both the meaning of the Qur’an and how Islam shapes daily life, teaching in Filipino and English.',
    bioAr: 'يخدم الجالية الفلبينية، يجمع علم الشريعة بخلفيّة في القانون.',
    longBioAr:
      'يحمل زين العابدين ماجستير الشريعة والقانون، ويخدم الجالية الفلبينية بمكة. يساعد المسلمين الجدد على فهم معاني القرآن وكيف يشكّل الإسلام الحياة اليوميّة، ويعلّم بالفلبينية والإنجليزية.',
    avatar: '/translators/zain-al-abidin.jpg',
    cover: '/translators/zain-al-abidin.jpg',
    subjects: ['tafseer', 'fiqh'],
    languages: ['Filipino', 'English', 'Arabic'],
    rating: 4.9,
    reviewCount: 58,
    studentCount: 640,
    sessionPriceUsd: 0,
    sessionsCompleted: 870,
    yearsTeaching: 10,
    availability: ['Mon 5pm', 'Wed 7pm', 'Sat 2pm'],
    verified: true,
  },
  {
    slug: 'akhyar-rashidi',
    name: 'Akhyar Rashidi',
    nameAr: 'أخيار راشدي راشدي رايف',
    title: "Da'i to the Indonesian Community",
    community: 'Indonesian Community',
    communityAr: 'الجالية الإندونيسية',
    qualification: "Bachelor's in Hadith & Islamic Studies",
    qualificationAr: 'بكالوريوس في الحديث والدراسات الإسلامية',
    phone: '+966 50 929 871',
    email: 'Abunowwaf81@gmail.com',
    bio: 'Teaches the Indonesian community the life of the Prophet ﷺ and the foundations of the deen.',
    longBio:
      'Akhyar Rashidi holds a Bachelor’s in Hadith and Islamic Studies and serves the Indonesian community of Makkah. He is known for bringing the Seerah to life and grounding new Muslims in the sound narrations of the Prophet ﷺ, teaching in Indonesian.',
    bioAr: 'يعلّم الجالية الإندونيسية سيرة النبيّ ﷺ وأصول الدين.',
    longBioAr:
      'يحمل أخيار راشدي بكالوريوس الحديث والدراسات الإسلامية، ويخدم الجالية الإندونيسية بمكة. يُعرف بإحيائه للسيرة النبويّة وترسيخه المسلمين الجدد على الروايات الصحيحة، ويعلّم بالإندونيسية.',
    avatar: '/translators/akhyar-rashidi.jpg',
    cover: '/translators/akhyar-rashidi.jpg',
    subjects: ['seerah', 'arabic', 'hadith'],
    languages: ['Indonesian', 'Arabic'],
    rating: 4.9,
    reviewCount: 47,
    studentCount: 520,
    sessionPriceUsd: 0,
    sessionsCompleted: 690,
    yearsTeaching: 9,
    availability: ['Tue 5pm', 'Thu 7pm', 'Sun 3pm'],
    verified: true,
  },
];

export function getTeacher(slug: string): Teacher | undefined {
  return teachers.find((t) => t.slug === slug);
}

export function teachersBySubject(subjectSlug: string): Teacher[] {
  return teachers.filter((t) => t.subjects.includes(subjectSlug as never));
}

export const teacherContent: TeacherContent[] = [
  {
    id: 'c-1',
    teacherSlug: 'mansour-golam',
    subjectSlug: 'quran',
    title: 'How to begin reading the Qur’an — without overwhelm',
    type: 'video',
    excerpt:
      'A gentle starter for new Muslims: alphabet recognition, sound mapping, and what to actually practice on day one.',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    thumbnail: '/teachers/lesson-quran-1.jpg',
    durationMin: 14,
    views: 8420,
    publishedAt: '2026-02-12',
  },
  {
    id: 'c-2',
    teacherSlug: 'mansour-golam',
    subjectSlug: 'tajweed',
    title: 'The five makharij — making the sounds correctly',
    type: 'text',
    excerpt:
      'A short written guide to where each Arabic letter actually originates in the mouth and throat.',
    body: 'Every letter of the Arabic alphabet emerges from a specific place in the mouth, throat or lips. The classical scholars grouped these into five major regions — al-jawf, al-halq, al-lisan, al-shafatayn and al-khayshum. Understanding these regions is the first step toward reciting correctly...',
    durationMin: 6,
    views: 5210,
    publishedAt: '2026-03-04',
  },
  {
    id: 'c-3',
    teacherSlug: 'akhyar-rashidi',
    subjectSlug: 'arabic',
    title: 'Why Arabic feels hard — and what to do instead',
    type: 'video',
    excerpt:
      'A reframing of how new Muslims often approach Arabic and three practical changes you can make today.',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    thumbnail: '/teachers/lesson-arabic-1.jpg',
    durationMin: 22,
    views: 6310,
    publishedAt: '2026-01-29',
  },
  {
    id: 'c-4',
    teacherSlug: 'zain-al-abidin',
    subjectSlug: 'tafseer',
    title: 'Surat al-Fatiha — verse one, opened up',
    type: 'text',
    excerpt:
      'A close reading of "Bismillah ir-Rahman ir-Raheem" with the meanings the scholars drew from each word.',
    body: 'The first words a Muslim says before almost any act of significance: "Bismillah ir-Rahman ir-Raheem". Each word carries weight. The "ba" of seeking help. The Name "Allah" — the most specific Name. Then two of the Most Beautiful Names: Ar-Rahman and Ar-Raheem...',
    durationMin: 9,
    views: 4720,
    publishedAt: '2026-02-19',
  },
  {
    id: 'c-5',
    teacherSlug: 'jamil-al-rahman',
    subjectSlug: 'fiqh',
    title: 'Wudu: the simplest possible explanation',
    type: 'video',
    excerpt:
      'A clean, step-by-step walkthrough of how to make wudu with nothing skipped and nothing extra.',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    thumbnail: '/teachers/lesson-fiqh-1.jpg',
    durationMin: 11,
    views: 9120,
    publishedAt: '2026-03-11',
  },
  {
    id: 'c-6',
    teacherSlug: 'mohamed-thani-ahmed',
    subjectSlug: 'aqeedah',
    title: 'Who is Allah? The first thing a new Muslim should know',
    type: 'text',
    excerpt: 'The grounding belief that holds everything else together — explained in plain language.',
    body: 'Before any rule, before any prayer, before any fast — there is the question of who Allah is. The Qur’an answers this directly and repeatedly...',
    durationMin: 8,
    views: 7530,
    publishedAt: '2026-02-02',
  },
  {
    id: 'c-7',
    teacherSlug: 'akhyar-rashidi',
    subjectSlug: 'seerah',
    title: 'The first revelation — the cave of Hira',
    type: 'video',
    excerpt: 'Walk into the cave with the Prophet ﷺ on the night that changed the world.',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    thumbnail: '/teachers/lesson-seerah-1.jpg',
    durationMin: 28,
    views: 11200,
    publishedAt: '2026-03-21',
  },
  {
    id: 'c-8',
    teacherSlug: 'mansour-golam',
    subjectSlug: 'quran',
    title: 'Memorize Surat an-Nas in 20 minutes',
    type: 'video',
    excerpt: 'A guided memorization session — repeat with me, three ayahs at a time.',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    thumbnail: '/teachers/lesson-hifdh-1.jpg',
    durationMin: 20,
    views: 6840,
    publishedAt: '2026-03-02',
  },
];

export function contentByTeacher(slug: string): TeacherContent[] {
  return teacherContent.filter((c) => c.teacherSlug === slug);
}

export function getContent(id: string): TeacherContent | undefined {
  return teacherContent.find((c) => c.id === id);
}
