import type { Teacher, TeacherContent } from '@/types/teacher';

export const teachers: Teacher[] = [
  {
    slug: 'sh-yusuf-bilal',
    name: 'Sh. Yusuf Bilal',
    title: 'Senior Quran & Tajweed Instructor',
    bio: 'Ijazah in Hafs ‘an ‘Asim. Fifteen years teaching new Muslims across three continents.',
    longBio:
      'Sh. Yusuf received his ijazah in the recitation of Hafs from his teacher in Madinah and went on to spend three years studying Tajweed under Sh. Ayman Suwayd. He has taught new Muslims since 2010 across the UK, Egypt and the US — and his sessions are known for their patience and warmth.',
    avatar: '/teachers/yusuf.jpg',
    cover: '/teachers/cover-quran.jpg',
    subjects: ['quran', 'tajweed'],
    languages: ['English', 'Arabic'],
    rating: 4.9,
    reviewCount: 218,
    studentCount: 1240,
    sessionPriceUsd: 0,
    sessionsCompleted: 2100,
    yearsTeaching: 15,
    availability: ['Mon 6pm', 'Wed 8pm', 'Sat 10am'],
    verified: true,
  },
  {
    slug: 'ust-amina-haq',
    name: 'Ust. Amina Haq',
    title: 'Arabic & Tafseer Specialist',
    bio: 'Al-Azhar graduate. Helps new sisters fall in love with Arabic without the fear.',
    longBio:
      'Ust. Amina holds a BA in Arabic Language from Al-Azhar University and an MA in Tafseer from IIUM. Her teaching method focuses on intuitive grammar and verse-by-verse Tafseer paced for new Muslims.',
    avatar: '/teachers/amina.jpg',
    cover: '/teachers/cover-arabic.jpg',
    subjects: ['arabic', 'tafseer'],
    languages: ['English', 'Arabic', 'Urdu'],
    rating: 4.9,
    reviewCount: 174,
    studentCount: 980,
    sessionPriceUsd: 0,
    sessionsCompleted: 1620,
    yearsTeaching: 11,
    availability: ['Tue 11am', 'Thu 6pm', 'Sun 3pm'],
    verified: true,
  },
  {
    slug: 'sh-ibrahim-ali',
    name: 'Sh. Ibrahim Ali',
    title: 'Fiqh & Aqeedah Mentor',
    bio: 'Specializes in walking new Muslims through their first months of practice.',
    longBio:
      'Sh. Ibrahim studied at Umm al-Qura and has taught fiqh classes online since 2014. He’s known for slow, patient explanations and a calm, grounded approach to aqeedah.',
    avatar: '/teachers/ibrahim.jpg',
    cover: '/teachers/cover-fiqh.jpg',
    subjects: ['fiqh', 'aqeedah'],
    languages: ['English'],
    rating: 4.8,
    reviewCount: 156,
    studentCount: 760,
    sessionPriceUsd: 0,
    sessionsCompleted: 1180,
    yearsTeaching: 10,
    availability: ['Mon 7pm', 'Fri 8pm'],
    verified: true,
  },
  {
    slug: 'ust-khadija-noor',
    name: 'Ust. Khadija Noor',
    title: 'Seerah & Hadith Teacher',
    bio: 'Tells the story of the Prophet ﷺ like you’re sitting with the Companions.',
    longBio:
      'Ust. Khadija is a graduate of the Cambridge Muslim College Diploma in Islamic Studies. Her seerah classes weave hadith narrations with vivid storytelling, paced gently for new Muslims.',
    avatar: '/teachers/khadija.jpg',
    cover: '/teachers/cover-seerah.jpg',
    subjects: ['seerah', 'hadith'],
    languages: ['English', 'French'],
    rating: 4.9,
    reviewCount: 142,
    studentCount: 690,
    sessionPriceUsd: 0,
    sessionsCompleted: 940,
    yearsTeaching: 8,
    availability: ['Wed 6pm', 'Sat 1pm'],
    verified: true,
  },
  {
    slug: 'sh-omar-faruq',
    name: 'Sh. Omar Faruq',
    title: 'Quran Memorization Coach',
    bio: 'Hafiz al-Qur’an with a structured method for new Muslims memorizing their first surahs.',
    longBio:
      'Sh. Omar memorized the Qur’an at age 14 and has coached hundreds of new Muslims through their first juz. He uses a spaced-repetition method tailored to busy adults.',
    avatar: '/teachers/omar.jpg',
    cover: '/teachers/cover-hifdh.jpg',
    subjects: ['quran', 'tajweed', 'tafseer'],
    languages: ['English', 'Arabic'],
    rating: 4.7,
    reviewCount: 98,
    studentCount: 540,
    sessionPriceUsd: 0,
    sessionsCompleted: 720,
    yearsTeaching: 6,
    availability: ['Tue 7pm', 'Thu 7pm'],
    verified: true,
  },
  {
    slug: 'ust-mariam-saleh',
    name: 'Ust. Mariam Saleh',
    title: 'Arabic Conversation Tutor',
    bio: 'Conversational Arabic for new Muslims who want to understand prayer first.',
    longBio:
      'Ust. Mariam holds an MA in Arabic Linguistics. Her classes focus on the language of the prayer first — meanings of every line you say five times a day.',
    avatar: '/teachers/mariam.jpg',
    cover: '/teachers/cover-arabic-2.jpg',
    subjects: ['arabic'],
    languages: ['English', 'Arabic', 'Spanish'],
    rating: 4.8,
    reviewCount: 87,
    studentCount: 420,
    sessionPriceUsd: 0,
    sessionsCompleted: 610,
    yearsTeaching: 7,
    availability: ['Mon 5pm', 'Sun 6pm'],
    verified: true,
  },
];

export function getTeacher(slug: string): Teacher | undefined {
  return teachers.find((t) => t.slug === slug);
}

export function teachersBySubject(subjectSlug: string): Teacher[] {
  return teachers.filter((t) => t.subjects.includes(subjectSlug as never));
}

export const teacherContent: TeacherContent[] = [
  {
    id: 'c-1',
    teacherSlug: 'sh-yusuf-bilal',
    subjectSlug: 'quran',
    title: 'How to begin reading the Qur’an — without overwhelm',
    type: 'video',
    excerpt:
      'A gentle starter for new Muslims: alphabet recognition, sound mapping, and what to actually practice on day one.',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    thumbnail: '/teachers/lesson-quran-1.jpg',
    durationMin: 14,
    views: 8420,
    publishedAt: '2026-02-12',
  },
  {
    id: 'c-2',
    teacherSlug: 'sh-yusuf-bilal',
    subjectSlug: 'tajweed',
    title: 'The five makharij — making the sounds correctly',
    type: 'text',
    excerpt:
      'A short written guide to where each Arabic letter actually originates in the mouth and throat.',
    body: 'Every letter of the Arabic alphabet emerges from a specific place in the mouth, throat or lips. The classical scholars grouped these into five major regions — al-jawf, al-halq, al-lisan, al-shafatayn and al-khayshum. Understanding these regions is the first step toward reciting correctly...',
    durationMin: 6,
    views: 5210,
    publishedAt: '2026-03-04',
  },
  {
    id: 'c-3',
    teacherSlug: 'ust-amina-haq',
    subjectSlug: 'arabic',
    title: 'Why Arabic feels hard — and what to do instead',
    type: 'video',
    excerpt:
      'A reframing of how new Muslims often approach Arabic and three practical changes you can make today.',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    thumbnail: '/teachers/lesson-arabic-1.jpg',
    durationMin: 22,
    views: 6310,
    publishedAt: '2026-01-29',
  },
  {
    id: 'c-4',
    teacherSlug: 'ust-amina-haq',
    subjectSlug: 'tafseer',
    title: 'Surat al-Fatiha — verse one, opened up',
    type: 'text',
    excerpt:
      'A close reading of "Bismillah ir-Rahman ir-Raheem" with the meanings the scholars drew from each word.',
    body: 'The first words a Muslim says before almost any act of significance: "Bismillah ir-Rahman ir-Raheem". Each word carries weight. The "ba" of seeking help. The Name "Allah" — the most specific Name. Then two of the Most Beautiful Names: Ar-Rahman and Ar-Raheem...',
    durationMin: 9,
    views: 4720,
    publishedAt: '2026-02-19',
  },
  {
    id: 'c-5',
    teacherSlug: 'sh-ibrahim-ali',
    subjectSlug: 'fiqh',
    title: 'Wudu: the simplest possible explanation',
    type: 'video',
    excerpt:
      'A clean, step-by-step walkthrough of how to make wudu with nothing skipped and nothing extra.',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    thumbnail: '/teachers/lesson-fiqh-1.jpg',
    durationMin: 11,
    views: 9120,
    publishedAt: '2026-03-11',
  },
  {
    id: 'c-6',
    teacherSlug: 'sh-ibrahim-ali',
    subjectSlug: 'aqeedah',
    title: 'Who is Allah? The first thing a new Muslim should know',
    type: 'text',
    excerpt: 'The grounding belief that holds everything else together — explained in plain language.',
    body: 'Before any rule, before any prayer, before any fast — there is the question of who Allah is. The Qur’an answers this directly and repeatedly...',
    durationMin: 8,
    views: 7530,
    publishedAt: '2026-02-02',
  },
  {
    id: 'c-7',
    teacherSlug: 'ust-khadija-noor',
    subjectSlug: 'seerah',
    title: 'The first revelation — the cave of Hira',
    type: 'video',
    excerpt: 'Walk into the cave with the Prophet ﷺ on the night that changed the world.',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    thumbnail: '/teachers/lesson-seerah-1.jpg',
    durationMin: 28,
    views: 11200,
    publishedAt: '2026-03-21',
  },
  {
    id: 'c-8',
    teacherSlug: 'sh-omar-faruq',
    subjectSlug: 'quran',
    title: 'Memorize Surat an-Nas in 20 minutes',
    type: 'video',
    excerpt: 'A guided memorization session — repeat with me, three ayahs at a time.',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    thumbnail: '/teachers/lesson-hifdh-1.jpg',
    durationMin: 20,
    views: 6840,
    publishedAt: '2026-03-02',
  },
];

export function contentByTeacher(slug: string): TeacherContent[] {
  return teacherContent.filter((c) => c.teacherSlug === slug);
}

export function getContent(id: string): TeacherContent | undefined {
  return teacherContent.find((c) => c.id === id);
}
